#Intro title information
title: "RBL3 Analysis Report"
report_header_info:
    - FASTQ Analysis: 'Samples include those [determine what was done before fastq created]'
    - SAMStats Analysis: 'Sample include those after alignment'

#include fastqscreen
fastqscreen_simpleplot: true

#remove analysis paths from file
show_analysis_paths: False

#find samples
sp:
    fastq_screen:
        fn: '*_screen.txt'

module_order:
# Pre-alignment QC
    - 'fastqc'
    - 'fastq_screen'
    - 'samtools'