# Global configuration file for the pipeline
#path to rbl3 directory
sourceDir: "ls /data/RBL_NCI/Pipelines/Talon_Flair/v1.0/RBL_RBL3/"

#path to output directory
outputDir: "/path/to/output/dir/"

#path to manifest files
sampleManifest: "/path/to/sample_manifest.tsv"
DEGManifest: "/path/to/deg_manifest.tsv"

#path to fastq files
fastqDir: "/path/to/fastq_files"

#user parameters
maskedReference: "Y" #if a masked reference file (see below) should be used indicate "Y"
cleanTranscripts: "Y" #if Y Transcriptclean will be run - read feature info in documentation
annotationID: "SIRV_annot" #use as a label for annotation used
buildID: "SIRV" #use as a label for the build or version running
platformID: "Illumina" #use as a label for the platform sequenced
maxFracA: 0.5 #maximum fraction of A's in the window located immediately after any read assigned to a novel transcript; use 1 to not filter [Default: .5]
minCount: 5 #Number of minimum occurrences required for a novel transcript PER dataset [Default: 5]
minDatasets: 2 #Minimum number of datasets novel transcripts must be found in [Default: 2]
primerLength: 20 #match the length of the T sequence in your primer, [Default: 20]
percentSimilarity: 20 #lowest percentage of A in the 20bp interval after alignment [Default: 20]
numberMatches: 5 #least number of matched reads in replicates [Default: 5]

#ref files
annotationGTF: "/data/RBL_NCI/Pipelines/Talon_Flair/dependencies/gencode.v30.annotation.gtf"
annotationFA: "/data/RBL_NCI/Pipelines/Talon_Flair/dependencies/hg38_cleanheader.fa"

annotationGTFmasked: "/data/RBL_NCI/Pipelines/Talon_Flair/dependencies/masked_dgcr8/DGCR8.gtf"
annotationFAmasked: "/data/RBL_NCI/Pipelines/Talon_Flair/dependencies/masked_dgcr8/DGCR8.fa"

#modules, container parameters
condaDir: "/data/RBL_NCI/Pipelines/Talon_Flair/conda_envs/"
talonConda: "talon_0416.sif"
porechopConda: "porechop_0.2.4.sif"
flairConda: "ccbr_flair_v1.5.sif"

minimap2: "minimap2/2.17"
python: "python/3.7"
bedtools: "bedtools/2.29.2"
singularity: "singularity"
fastqc: "fastqc/0.11.9"
multiqc: "multiqc/1.9"
Qt: "Qt/5.13.2"
samtools: "samtools/1.11"
R: "R/4.0"
java: "java/12.0.1"
picard: "picard/2.25.0"