# Global configuration file for the pipeline
#path to rbl3 directory
source_dir: "/path/to/rbl3/repo/"

#path to output directory
output_dir: "/path/to/output/dir/"

#path to manifest files
sample_manifest: "/path/to/sample_manifest.tsv"
deg_manifest: "/path/to/deg_manifest.tsv"

#path to fastq files
fastq_dir: "/path/to/fastq_files"

#user parameters
masked_reference: "Y" #if a masked reference file (see below) should be used indicate "Y"
clean_transcripts: "Y" #if Y Transcriptclean will be run - read feature info in documentation
annotation_id: "SIRV_annot" #use as a label for annotation used
build_id: "SIRV" #use as a label for the build or version running
platform_id: "Illumina" #use as a label for the platform sequenced
maxFracA: 0.5 #maximum fraction of A's in the window located immediately after any read assigned to a novel transcript; use 1 to not filter [Default: .5]
minCount: 5 #Number of minimum occurrences required for a novel transcript PER dataset [Default: 5]
minDatasets: 2 #Minimum number of datasets novel transcripts must be found in [Default: 2]
primer_length: 20 #match the length of the T sequence in your primer, [Default: 20]
percent_similarity: 20 #lowest percentage of A in the 20bp interval after alignment [Default: 20]
number_of_matches: 5 #least number of matched reads in replicates [Default: 5]

#ref files
annotation_gtf: "/data/CCBR_Pipeliner/Talon_Flair/dependencies/gencode.v30.annotation.gtf"
annotation_fa: "/data/CCBR_Pipeliner/Talon_Flair/dependencies/hg38_cleanheader.fa"

annotation_gtf_masked: "/data/CCBR_Pipeliner/Talon_Flair/dependencies/masked_dgcr8/DGCR8.gtf"
annotation_fa_masked: "/data/CCBR_Pipeliner/Talon_Flair/dependencies/masked_dgcr8/DGCR8.fa"

#modules, container parameters
conda_dir: "/data/CCBR_Pipeliner/Talon_Flair/conda_envs/"
talon_conda: "talon_0416.sif"
porechop_conda: "porechop_0.2.4.sif"
flair_conda: "ccbr_flair_v1.5.sif"

minimap2: "minimap2/2.17"
python: "python/3.7"
bedtools: "bedtools/2.29.2"
singularity: "singularity"
fastqc: "fastqc/0.11.9"
multiqc: "multiqc/1.9"
Qt: "Qt/5.13.2"
samtools: "samtools/1.11"
R: "R/4.0"