$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

properties:
  sourceDir:
    type: string
    description: /path/to/talon_flair/dir
  outputDir:
    type: string
    description: /path/to/output/dir
  sampleManifest:
    type: string
    description: /path/to/sample/manifest
  DEGManifest:
    type: string
    description: /path/to/deg/manifest
  fastqDir:
    type: string
    description: /path/to/fastq/files
  cleanTranscripts:
    types: string
    enum: ["Y","N","y","n"]
    description: determine whether or not run TranscriptClean
  maxFracA:
    types: number
    description: maximum fraction of A's in the window located immediately after any read assigned to a novel transcript
  minCount:
    type: number
    description: Number of minimum occurrences required for a novel transcript PER dataset
  minDatasets:
    type: number
    description: Minimum number of datasets novel transcripts must be found in
  primerLength:
    type: number
    description: match the length of the T sequence in your primer
  percentSimilarity:
    type: number
    description: lowest percentage of A in the 20bp interval after alignment
  numberMatches:
    type: number
    description: least number of matched reads in replicates
  condaDir:
    type: string
    description: /path/to/conda/

# entries that have to be in the config file for successful validation
required:
  - sourceDir
  - outputDir
  - sampleManifest
  - DEGManifest
  - fastqDir
  - cleanTranscripts
  - maxFracA
  - minCount
  - minDatasets
  - primerLength
  - percentSimilarity
  - numberMatches
  - condaDir