$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

properties:
  source_dir:
    type: string
    description: /path/to/talon_flair/dir
  output_dir:
    type: string
    description: /path/to/output/dir
  sample_manifest:
    type: string
    description: /path/to/sample/manifest
  deg_manifest:
    type: string
    description: /path/to/deg/manifest
  fastq_dir:
    type: string
    description: /path/to/fastq/files
  clean_transcripts:
    types: string
    enum: ["Y","N","y","n"]
    description: determine whether or not run TranscriptClean
  maxFracA:
    types: number
    description: maximum fraction of A's in the window located immediately after any read assigned to a novel transcript
  minCount:
    type: number
    description: Number of minimum occurrences required for a novel transcript PER dataset
  minDatasets:
    type: number
    description: Minimum number of datasets novel transcripts must be found in
  primer_length:
    type: number
    description: match the length of the T sequence in your primer
  percent_similarity:
    type: number
    description: lowest percentage of A in the 20bp interval after alignment
  number_of_matches:
    type: number
    description: least number of matched reads in replicates
  conda_dir:
    type: string
    description: /path/to/conda/

# entries that have to be in the config file for successful validation
required:
  - source_dir
  - output_dir
  - sample_manifest
  - deg_manifest
  - fastq_dir
  - clean_transcripts
  - maxFracA
  - minCount
  - minDatasets
  - primer_length
  - percent_similarity
  - number_of_matches
  - conda_dir